# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1D1C1C)
$foreground = rgb(CBEFF3)
$color0 = rgb(434343)
$color1 = rgb(222C2F)
$color2 = rgb(253337)
$color3 = rgb(213F5E)
$color4 = rgb(365D63)
$color5 = rgb(468890)
$color6 = rgb(4F9EA6)
$color7 = rgb(ACE0E6)
$color8 = rgb(789DA1)
$color9 = rgb(2E3A3F)
$color10 = rgb(324449)
$color11 = rgb(2C547E)
$color12 = rgb(487D84)
$color13 = rgb(5EB6BF)
$color14 = rgb(69D2DD)
$color15 = rgb(ACE0E6)
