exec-once = blueman-applet
exec-once = qs
#exec-once = $scriptsDir/KeybindsLayoutInit.sh
exec-once = gnome-keyring-daemon --start --components=secrets
# force cursor on startup
exec-once = hyprctl setcursor macOS-White 24
